name: Prow-CI

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 3:30 AM UTC (9 AM IST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: golang:1.20

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4

      - name: Run Test and Store Output
        run: go run main.go prowjob summary-report > prowjob-output.txt

      - name: Send Slack Message
        run: go run main.go send-slack-message -m "$(cat prowjob-output.txt)"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          PROW_URL: ${{ secrets.PROW_URL }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
